cmake_minimum_required(VERSION 2.8.3)

file(READ "${CMAKE_CURRENT_LIST_DIR}/../src/evaluate_view_opencl.cl" CL_PROGRAM)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../src/opencl_cpp_common.h" CL_CPP_COMMON)
file(WRITE "${CMAKE_CURRENT_LIST_DIR}/../src/evaluate_view_opencl.cl.cpp" "// Generated by evaluate_view_opencl.cmake\n// from evaluate_view_opencl.cl\n#include <string>\n#include \"evaluate_view_opencl.cl.h\"\n const std::string EVALUATE_VIEW_OPENCL_CL = R\"f4bd72756(\n${CL_CPP_COMMON}\n${CL_PROGRAM})f4bd72756\";")
